---
title: "Index"
editor: source
format: html
editor_options: 
  chunk_output_type: console
---

# mp223-2023-aem-R-public

Repository with the materials of the course MP223 - Applied Econometrics Methods in the Social Sciences for summer Semester 2023 at the JLU.

## Course plan

This is an approximate course plan that is updated before each lecture with the slides and materials relevant for each lecture.

### Week 1. April 12. Lecture: Introduction. Ceteris Paribus and Selection Bias.

Slides:

-   [w01a-introduction](slides/w01a-introduction.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w01a-introduction.pdf)
-   [w01b-selection-bias](slides/w01b-selection-bias.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w01b-selection-bias.pdf)
-   [w01c-r-rstudio-intro](slides/w01c-r-rstudio-intro.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w01c-r-rstudio-intro.pdf)

Exercises:

-   [ex01-rct.zip](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/exercises/ex01-rct.zip) - the R project with code and data
-   Supplementary recording on how to execute the analysis <https://youtu.be/-ednrypEv4o>.

### Week 2. April. 19. MLR - Multiple Linear Regression (Lecture)

Slides: See Ilias.

### Week 3. April. 26. MLR and where it comes from? Hedonic model. Practice with MLR.

Slides:

-   [w03-mlr-part1](slides/w03-mlr-part1.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w03-mlr-part1.pdf)

Exercises + Recordings:

-   [ex03-regression-part1.zip](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/exercises/ex03-regression-part1.zip) - the R project with code and data
-   ex.03.a Regression basics <https://youtu.be/rUlpdHsXPRw>
-   ex.03.b Wage and Education <https://youtu.be/5zwYnnjnZXo>
-   ex.03.c Hedonic regression <https://youtu.be/-tIylFJUNX4>

### Week 4. May 3. MLR. Production function. Linear transformation. Assumptions validation.

Slides:

-   [w04-mlr-part2](slides/w04-mlr-part2.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w04-mlr-part2.pdf)

Exercises:

-   [ex04-regression-part2.zip](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/exercises/ex04-regression-part2.zip) - the R project with code and data
-   ex.04.b Complex production function <https://youtu.be/DMxFupZSzTs>

### Week 5. May 10. Impact Evaluation: Counterfactual and DID (Lecture)

Slides: See Ilias.

### Week 6. May 17. Interaction terms and DiD. R: DID.

Slides:

-   [w06a-interactions](slides/w06a-interactions.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w06a-interactions.pdf)

    -   Pre-recorded materials on interaction term <https://youtu.be/2M4LRVGPgoI>

-   [w06b-DiD](slides/w06b-DiD.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w06b-did.pdf)

Exercises:

-   [ex06-did-and-interactions.zip](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/exercises/ex06-did-and-interactions.zip) - the R project with code and data

    -   ex.06.a Interaction terms <https://youtu.be/GJLt36FAj48>
    -   ex.06.b DiD <https://youtu.be/QAI3-Rh1Sok>
    -   ex.06.C DiD Card Krueger <https://youtu.be/ogaVyGCO_6c>

### Week 7. May 24. OVB - Omitted Variable Bias (Lecture). OBV formula

Slides:

-   [w07-OVB](slides/w07-OVB.qmd) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/w07-OVB.pdf)

    -   w07 OVB Lecture <https://youtu.be/AM6fhMby0W4>

Exercises:

-   [ex07-ovb.zip](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/exercises/ex07-ovb.zip) - R project with code and data

    -   ex.07.a Wage, Education and ability <https://youtu.be/x3g9z63xqFE>
    -   ex.07.b Wage, union membership and education <https://youtu.be/EJhmkJGLsBc>

### Week 8. May 31. FE - Fixed Effect / Panel Regression (Lecture)

Slides:

-   **After the lecture**

-   [w08a-panel-regression](slides/) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/)

-   [w08b-panel-regression-production-function.qmd](slides/) + [pdf](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/files/)

Exercises:

-   [ex08-panel-regression.zip](https://github.com/EBukin/mp223-2023-aem-R-public/raw/main/exercises/ex08-panel-regression.zip) - R project with code and data



### Week 9. June 7. R: FE

### Week 10. June 14. RDD - Regression Discontinuity (Lecture) + R: RDD

### Week 11. June 21. IV - Instrumental Variable (Lecture) + R: IV

### Week 12. June 28. Binary outcome variable (Lecture)

### Week 13. July 5. R: Binary outcome variable

### Week 14. July 12. No class (POssible QA session on demand)

### Week 15. July 19. Final Exam
